---
apiVersion: v1
kind: Service
metadata:
  name: go-crypto-exchange-service
spec:
  type: LoadBalancer 
  selector:
    app: go-crypto-exchange-app
  ports:
    - protocol: TCP
      nodePort: 31000
      port: 80
      targetPort: http 
