apiVersion: v1
kind: Service
metadata:
    name: go-crypto-exchange-service
spec:
    selector:
        app: go-crypto-exchange-app
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
          nodePort: 30000
