---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-crypto-exchange-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: go-crypto-exchange-app
  template:
    metadata:
      labels:
        app: go-crypto-exchange-app
    spec:
      affinity:
        # ⬇⬇⬇ This ensures pods will land on separate hosts
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions: [{ key: app, operator: In, values: [go-crypto-exchange-app] }]
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: go-crypto-exchange-app
        image: theflilux1402/crypto-exchange-backend
        ports:
          - name: http
            containerPort: 80
      terminationGracePeriodSeconds: 1
