name: crypto_exchange_frontend
description: Frontend for Crypto Exchange project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  shared_preferences: ^2.2.3
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 5c51870ced62a00e809ba4b81a846a052d241c9f
  fluent_ui: ^4.8.7
  provider: ^6.1.2
  flutter_secure_storage: ^9.1.1
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  rsa_encrypt: ^2.0.0

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
  msix: ^3.16.7
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Italic.ttf
        - asset: fonts/RobotoMono-Variable.ttf
          style: italic

flutter_icons:
  android: false
  ios: false
  image_path: "assets/app-logo.png"
  web:
    generate: true
    image_path: "assets/app-logo.png"
  windows:
    generate: true
    image_path: "assets/app-logo.png"
    icon_size: 256

# Compile with: >flutter pub run msix:publish
msix_config:
  display_name: Toy Cryptocurrency
  publisher_display_name: Piero Morales
  identity_name: com.toy.cryptocurrency.utec
  app_installer:
    publish_folder_path: C:\Users\piero\Downloads\Toy_Cryprocurrency_Deploy
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: true
  store: false
  debug: false
  publisher: C=PE, ST=Lima, L=Lima, O=UTEC, OU=UTEC, CN=Piero Morales, emailAddress=sanjuan.pama@gmail.com
  certificate_path: C:\Users\piero\CERTIFICATE.pfx
  certificate_password: SanJuan1603
  sign_msix: true
  install_certificate: true
  msix_version: 1.0.0.0
  logo_path: C:\Users\piero\StudioProjects\Toy_Cryptocurrency_Frontend\assets\app-logo.png
  languages: en-us, es-es
  architecture: x64
  capabilities: internetClient
